//! Byte-gate for the GENERATED heuristics ledger (cute-dbt#169).
//!
//! The single source of truth for every check is the `heuristics!` block
//! in `src/domain/checks.rs`; the committed `heuristics/registry.toml` +
//! the book check pages under `book/src/checks/` are **generated output**
//! (design sketch §5b — the clippy `declare_lint!` + example-report-check
//! architecture). This test is the sync guarantee:
//!
//! - **Default mode** (`cargo test --test heuristics_ledger`):
//!   regenerate every artifact in memory and assert byte-identity with
//!   the committed file — drift fails the build with the regeneration
//!   command in the message.
//! - **Write mode** (`GEN_HEURISTICS_LEDGER=1 cargo test --test
//!   heuristics_ledger`): write the regenerated artifacts in place (the
//!   `heuristics-ledger` CI job runs this then `git diff --exit-code`,
//!   mirroring `example-report-check`; `lefthook.yml` carries the local
//!   mirror).
//!
//! Two drift directions beyond content are also pinned: a check page on
//! disk that no registered check generates (stale file), and a generated
//! page missing from `book/src/SUMMARY.md` (mdbook nav rot).

use std::fs;
use std::path::{Path, PathBuf};

use cute_dbt::domain::{
    CheckId, HeuristicId, check_page_markdown, checks_index_markdown, registry_toml,
};

/// The regeneration hint surfaced on every mismatch.
const REGEN_HINT: &str =
    "regenerate with: GEN_HEURISTICS_LEDGER=1 cargo test --test heuristics_ledger";

/// Repo-root-relative path joined onto `CARGO_MANIFEST_DIR`.
fn repo_path(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(relative)
}

/// Every generated artifact: (repo-relative path, generated content).
fn generated_artifacts() -> Vec<(String, String)> {
    let mut artifacts = vec![
        (
            "heuristics/registry.toml".to_owned(),
            registry_toml::<HeuristicId>(),
        ),
        (
            "book/src/checks/index.md".to_owned(),
            checks_index_markdown::<HeuristicId>(),
        ),
    ];
    for id in HeuristicId::ALL {
        artifacts.push((
            format!("book/src/checks/{}.md", id.as_str()),
            check_page_markdown(*id),
        ));
    }
    artifacts
}

/// `true` when the run should write the artifacts instead of comparing.
fn write_mode() -> bool {
    std::env::var("GEN_HEURISTICS_LEDGER").is_ok_and(|v| v == "1")
}

#[test]
fn committed_ledger_is_byte_identical_to_generated_output() {
    for (relative, generated) in generated_artifacts() {
        let path = repo_path(&relative);
        if write_mode() {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).expect("ledger directory creates");
            }
            fs::write(&path, &generated).expect("ledger artifact writes");
            continue;
        }
        let committed = fs::read_to_string(&path).unwrap_or_else(|err| {
            panic!("{relative} is missing or unreadable ({err}); {REGEN_HINT}")
        });
        assert_eq!(
            committed, generated,
            "{relative} drifted from the heuristics! block; {REGEN_HINT}"
        );
    }
}

#[test]
fn no_stale_check_pages_exist_on_disk() {
    // Deleting a check from the registry must also delete its committed
    // page — a stale page is silent doc rot the byte-compare above can't
    // see (it only walks the GENERATED set).
    if write_mode() {
        // Write mode regenerates files in a sibling test running in
        // parallel — directory contents are mid-flight here, so the
        // stale check is meaningless (the follow-up compare run gates it).
        return;
    }
    let dir = repo_path("book/src/checks");
    let expected: Vec<String> = generated_artifacts()
        .into_iter()
        .filter_map(|(relative, _)| relative.strip_prefix("book/src/checks/").map(str::to_owned))
        .collect();
    for entry in fs::read_dir(&dir).expect("book/src/checks exists") {
        let name = entry
            .expect("dir entry reads")
            .file_name()
            .to_string_lossy()
            .into_owned();
        assert!(
            expected.contains(&name),
            "book/src/checks/{name} is not generated by any registered check; \
             delete it (or register the check); {REGEN_HINT}"
        );
    }
}

#[test]
fn every_check_page_is_wired_into_the_book_summary() {
    // mdbook renders only SUMMARY-listed chapters; an unlisted generated
    // page would build green but be unreachable. Adding a check therefore
    // requires the one-line SUMMARY entry — this pins it.
    let summary = fs::read_to_string(repo_path("book/src/SUMMARY.md")).expect("book SUMMARY reads");
    assert!(
        summary.contains("(./checks/index.md)"),
        "book/src/SUMMARY.md must link ./checks/index.md"
    );
    for id in HeuristicId::ALL {
        let link = format!("(./checks/{}.md)", id.as_str());
        assert!(
            summary.contains(&link),
            "book/src/SUMMARY.md must link {link} for check {}",
            id.as_str()
        );
    }
}
